# Generated by Django 2.2.16 on 2022-05-24 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribitions', to=settings.AUTH_USER_MODEL)),
                ('user_to_subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('subscribing_user', 'user_to_subscribe'), name='unique_subscribe'),
        ),
    ]
